version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  
  build:
    commands:
      - echo "Iniciando criação do bucket via CloudFormation..."
      - aws cloudformation deploy \
          --template-file s3.yaml \
          --stack-name criar-bucket-templates \
          --capabilities CAPABILITY_NAMED_IAM
      - echo "Bucket criado com sucesso! :)"
