version: 0.2

env:
  variables:
    BUCKET_NAME: projeto-devops-templates
    REGION: us-east-1

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Subindo templates filhos para o bucket S3..."
      - aws s3 cp cloudformation/infra/vpc.yaml s3://$BUCKET_NAME/templates/vpc.yaml
      - aws s3 cp cloudformation/infra/rds.yaml s3://$BUCKET_NAME/templates/rds.yaml
      - aws s3 cp cloudformation/infra/roles.yaml s3://$BUCKET_NAME/templates/roles.yaml
      - aws s3 cp cloudformation/infra/ec2.yaml s3://$BUCKET_NAME/templates/ec2.yaml

      - echo "Criando stack principal com nested stacks..."
      - aws cloudformation deploy \
          --template-file main.yaml \
          --stack-name stack-principal-infra \
          --capabilities CAPABILITY_NAMED_IAM \
          --region $REGION
