AWSTemplateFormatVersion: '2010-09-09'
Description: Criação de RDS PostgreSQL com Security Group e SubnetGroup

Parameters:
  DBUsername:
    Type: String
    Description: db_admin
    Default: admin
  DBPassword:
    Type: String
    Description: 758196Dj@
    NoEcho: true
  DBName:
    Type: String
    Description: users_db
    Default: mydb
  VPCId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso ao banco de dados RDS
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EC2SecurityGroupId

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group para o RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  MyDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mydb-instance
      Engine: postgres
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 1

Outputs:
  DBEndpoint:
    Description: Endpoint do banco de dados
    Value: !GetAtt MyDatabase.Endpoint.Address

  DBSecurityGroup:
    Description: ID do SG do banco
    Value: !Ref RDSSecurityGroup