AWSTemplateFormatVersion: '2010-09-09'
Description: Criação de bucket S3 para armazenar templates CloudFormation

Resources:
  TemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: projeto-devops-templates
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: projeto-devops-templates
    Value: !Ref TemplateBucket
  BucketArn:
    Description: ARN do bucket
    Value: !GetAtt TemplatesBucket.Arn