AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline CI/CD para provisionamento da infraestrutura
 
Resources:
 
  InfraPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: pipeline-infraestrutura
      RoleArn: !ImportValue CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: projeto-devops-artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: jaquelineolimpio
                Repo: Projeto_DevOps
                Branch: main
                OAuthToken: '{{resolve:secretsmanager:GitHubToken:SecretString:token}}'
              RunOrder: 1
 
        - Name: BuildBucket
          Actions:
            - Name: Build-Bucket
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BucketBuildOutput
              Configuration:
                ProjectName: criar-bucket-s3
              RunOrder: 1
 
        - Name: BuildMainInfra
          Actions:
            - Name: Build-Infrastructure
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: criar-infra-principal
              RunOrder: 1